# Loads default set of integrations. Do not remove.
default_config:

# Enable the packages folder
homeassistant:
  packages: !include_dir_named packages

# Optional: themes (only if you actually have a /config/themes folder)
frontend:
  themes: !include_dir_merge_named themes

# Lovelace dashboards
lovelace:
  mode: storage
  dashboards:
    dashboard-smart-home-hub:
      mode: yaml
      title: Smart Home Hub
      icon: mdi:home-analytics
      show_in_sidebar: true
      filename: dashboards/dashboard_v2.yaml

# Existing includes (fine as-is)
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
